version: '2.3'
services:
    shell:
        build: .
        volumes:
            - $PWD:/root/workspace
        working_dir: /root/workspace
        runtime: nvidia
        ipc: host
        environment:
            - TZ=Asia/Tokyo
            - LD_LIBRARY_PATH=/usr/local/cuda/lib64
        entrypoint: bash
    python:
        build: .
        volumes:
            - $PWD:/root/workspace
        working_dir: /root/workspace
        runtime: nvidia
        ipc: host
        environment:
            - TZ=Asia/Tokyo
            - LD_LIBRARY_PATH=/usr/local/cuda/lib64
        entrypoint: python
    jn:
        build: .
        volumes:
            - $PWD:/root/workspace
        working_dir: /root/workspace/notebooks
        runtime: nvidia
        ipc: host
        environment:
            - TZ=Asia/Tokyo
            - LD_LIBRARY_PATH=/usr/local/cuda/lib64
        ports:
            - 8888:8888
        command: jupyter notebook --port 8888 --ip=0.0.0.0 --allow-root
