version: '2.3'
services:
    python:
        build: .
        volumes:
            - $PWD:/root/workspace
            - $HOME/mnt:/root/mnt
        working_dir: /root/workspace
        runtime: nvidia
        environment:
            - TZ=Asia/Tokyo
            - LD_LIBRARY_PATH=/usr/local/cuda/lib64
        ports:
            - 6900:6900
        entrypoint: python
    jn:
        build: .
        volumes:
            - $PWD:/root/workspace
            - $HOME/mnt:/root/mnt
        working_dir: /root/workspace/notebooks
        runtime: nvidia
        environment:
           - TZ=Asia/Tokyo
            - LD_LIBRARY_PATH=/usr/local/cuda/lib64
        ports:
            - 8888:8888
        command: jupyter notebook --port 8888 --ip=0.0.0.0 --allow-root
